### ISSUE TITLE
release?

### ISSUE THREAD

**Issue by paulle** [SecUSo/privacy-friendly-todo-list#1]
I'm very interested in this app. When it will be released on f-droid? I don't know to code and cannot read it, so I have no idea if this app in an early stage of development or not. Excuse my curiosity.

**Comment by null0x** [comment]
This app should be released soon on F-Droid. Please check again in a few a days.

**Comment by Yonjuni** [comment]
We are planning to release it within the next week.

**Comment by Yonjuni** [comment]
All Privacy Friendly Apps will be submitted to F-Droid one after another ;)

**Comment by paulle** [comment]
Thank you for Information.

Am 19. November 2016 20:08:41 MEZ, schrieb Karola Marky <notifications@github.com>:
>All Privacy Friendly Apps will be submitted to F-Droid one after
>another ;)
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/SecUSo/privacy-friendly-todo-list/issues/1#issuecomment-261733097

-- 
K-9 Mail

**Comment by Yonjuni** [comment]
Submission sent. 
https://f-droid.org/forums/topic/privacy-friendly-to-do/
