### ISSUE TITLE
Add undo option

### ISSUE THREAD

**Issue by spiliot** [SecUSo/privacy-friendly-todo-list#10]
Accidentally marking a task as done can't be undone easily.

This is even worse in long lists of tasks and/or when the user didn't notice which task was marked as done.

**Comment by Yonjuni** [comment]
I understand the scenario as the following: You mark the task as done by the checkbox.
By clicking the checkbox again, the task is unmarked. 
Could you explain your comment in a bit more detail so that I can understand it better?

**Comment by spiliot** [comment]
Assuming a list is selected to show only "open" tasks (not marked as done) an accidentally marked task will disappear immediately off the list. Returning to show all tasks might not help identify which was the changed task, especially in long task lists.

**Comment by Yonjuni** [comment]
Okay, so something like a snackbar showing an undo button would help then.

**Comment by spiliot** [comment]
Yes, that would be an excellent fit!

**Comment by PeterHindes** [comment]
I believe this has been implimented. Please close the issue.

**Comment by Kamuno** [comment]
> I believe this has been implimented. Please close the issue.

You are indeed correct. Thank you
