### ISSUE TITLE
Re-order, organize sub-tasks

### ISSUE THREAD

**Issue by palikacska** [SecUSo/privacy-friendly-todo-list#100]
This is a feature request for sub-tasks in Privacy Friendly Todo List. It would be very useful if they could be re-ordered. For example, if some sub-task pops into my mind later but already added sub-tasks depend on it, it would give me more overall clarity to move that sub-tasks up.

**Comment by 0xC0FFEEC0DE** [comment]
PR #130 implements this feature.
