### ISSUE TITLE
Export todo list

### ISSUE THREAD

**Issue by udenr** [SecUSo/privacy-friendly-todo-list#102]
Add option to export a todo list to a simple text file

**Comment by 0xC0FFEEC0DE** [comment]
Backup App can do a backup of the todo lists and save the backup as text file. Is that sufficient?
If not, what is the purpose of the text file? Should it be human-readable? Or shoult it have a specific file format (JSON, XML, iCalendar, ...) for further processing?

**Comment by udenr** [comment]
I think the general idea with this and #101 is that you might want to share your list with others or create a list based on some data you received.
As we don't know in what stlye people keep their notes, the only two important requirement would be that if you export an simple list and import it again it should be the same (except special features like reminders, etc.) and that it is human-readable to share with others.
One option would be to use some markdown-stlye format, e.g.
```md
- [x] #101
- [ ] #102
```

**Comment by 0xC0FFEEC0DE** [comment]
Note: The use case behind issue #117 requires the realization of this enhancment and furthermore, that the format of the export file is not only human-readable but also machine-readable, in best case directly processable by common tools like OpenOffice calc or Microsoft Excel.

**Comment by 0xC0FFEEC0DE** [comment]
Hello @udenr , is CSV export / import (see #127) suitable to solve this issue and #101?
It is not as simple and intuitive as the markdown-stlye format but able to export / import lists, tasks and subtasks with all properties.

**Comment by udenr** [comment]
I think that's fine.
If someone needs a different feature (e.g., to share a todo list as human-readable text via a messenger), they can create a new one.

**Comment by 0xC0FFEEC0DE** [comment]
I could create a share menu entry.
Currently I'm redesigning the list edit button to a context menu. Its easily extendable by such an entry.
