### ISSUE TITLE
Add export function

### ISSUE THREAD

**Issue by thoys1** [SecUSo/privacy-friendly-todo-list#15]
A Funktion to export all todo items.

**Comment by paulle** [comment]
yes an export function (with the possibility to export to external sd-card) woud be great.

**Comment by tomikmar** [comment]
I just reinstalled my system and possibility to export and import data would be more than useful.

Maybe you could reuse some already existing plain text data format e.g. http://todotxt.com/ or something similar.

**Comment by paulle** [comment]
Export/import data, please add, because changing phone or reinstall the system all data is lost.

**Comment by petermayer** [comment]
Hi, we are aware of the issue. We are currently looking into making Import/Export/Synchronisation available for multiple of our apps. Unfortunately, I cannot give a time frame for this functionality's availability.

**Comment by paulle** [comment]
Thank you for looking at this, import/export function is really missing.

**Comment by PeterHindes** [comment]
Any progress on this? Would you be interested in a pull request?

**Comment by paulle** [comment]
This would be nice.

Am 19. Februar 2020 16:18:24 MEZ schrieb Peter Hindes <notifications@github.com>:
>Any progress on this? Would you be interested in a pull request?
>

-- 
Mit K-9 Mail gesendet.

**Comment by Kamuno** [comment]
Data Export has now been implemented via the Privacy Friendly Backup App.

**Comment by thoys1** [comment]
O.k. ---- thank you all!

**Comment by paulle** [comment]
Thank you from my side too

Gesendet von Proton Mail für Mobilgeräte

-------- Original-Nachricht --------
Am 13. Sept. 2022, 14:26, schrieb thoys1 :
