### ISSUE TITLE
Progress bar and subtask

### ISSUE THREAD

**Issue by Bobcadence** [SecUSo/privacy-friendly-todo-list#22]
### The progress bar advancement could be linked to the number of sub-tasks done?
It could be like this.

![screenshot_2017-01-20-17-18-25](https://cloud.githubusercontent.com/assets/25250338/22156774/1a5e4018-df35-11e6-81a6-c408b8118b5c.png)

I think it more visual. 

Now:
![screenshot_2017-01-20-17-18-00](https://cloud.githubusercontent.com/assets/25250338/22156766/13f06d6e-df35-11e6-98d0-b5bab420c3d5.png)

**Comment by Yonjuni** [comment]
Thanks for reporting. It actually was a design decision to separate it. I guess a good middle course would be providing a setting, such that the user can decide whether the progress bar is set by the sub tasks or not.

**Comment by Bobcadence** [comment]
This feature is still strange to me,a **productive** tool (your App) with **manual** indicator.... Why not?
Nevertheless, I understand the design decision. sub-tasks don't use the same duration to be done.
I agree with you a setting would be a good compromise.

**Comment by Yonjuni** [comment]
In version 2.0 the setting is included.
