### ISSUE TITLE
[Request] Show PIN keyboard by default

### ISSUE THREAD

**Issue by github-throwaway** [SecUSo/privacy-friendly-todo-list#25]
**Problem**
Currently you need to tap the input field so the number pad shows up, of you PIN protect your to-do list.

**Solution**

Show the number pad straight away so the user does not have to perform this extra tap.

**Comment by 0xC0FFEEC0DE** [comment]
Hello @github-throwaway , commit [ad85fbb](https://github.com/SecUSo/privacy-friendly-todo-list/commit/ad85fbb0d6b05e9c07b4d6cb1ea1b2279eabdb26) solves this issue.
