### ISSUE TITLE
App forgets location when switching away and back again

### ISSUE THREAD

**Issue by randomguy3** [SecUSo/privacy-friendly-todo-list#26]
App version: 1.0.1
Android version: 6.0.1 (Sony variant)

Steps to reproduce:
1. Open the To-Do List app
2. Press on a todo list to display the items
3. Switch to another app
4. Switch back to To-Do List

Expected behaviour: the To-Do list app still displays the previously-selected todo list.

Actual behaviour: the To-Do list has gone back to the starting screen (the list of todo lists).

**Comment by randomguy3** [comment]
NB: locking the screen also triggers this.

**Comment by Yonjuni** [comment]
Is connected to https://github.com/SecUSo/privacy-friendly-todo-list/issues/13 and will be solved with https://github.com/SecUSo/privacy-friendly-todo-list/issues/13

**Comment by Yonjuni** [comment]
Closed #26
