### ISSUE TITLE
App forgets filter selection

### ISSUE THREAD

**Issue by randomguy3** [SecUSo/privacy-friendly-todo-list#27]
App version: 1.0.1
Android version: 6.0.1 (Sony variant)

Steps to reproduce:
1. Open the To-Do List app
2. Press on a todo list to display the items
3. Mark some todo items as completed, and some as open
4. From the "..." menu (top right), select "Open tasks" to only display open tasks
5. Press back to return to the main screen
6. Select the list again

Expected behaviour: the list is still only showing open tasks

Actual behaviour: the To-Do list has gone back to displaying all tasks

NB: this is particularly annoying with #26.

**Comment by Yonjuni** [comment]
Connected to: https://github.com/SecUSo/privacy-friendly-todo-list/issues/13

**Comment by sleep-yearning** [comment]
Should be fixed, short testing also confirmed this. Feel free to reopen if problems occur.
