### ISSUE TITLE
Context menu instead of dialog onLongPress

### ISSUE THREAD

**Issue by Yonjuni** [SecUSo/privacy-friendly-todo-list#29]

**Comment by 0xC0FFEEC0DE** [comment]
Hello @Yonjuni , please could you provide more details on this issue? Thanks.

**Comment by 0xC0FFEEC0DE** [comment]
I think/hope 7bcf26af8dd4088d12ed12cad2ae34675937ca6b matches the intention of this issue.
Because I got no more input to the issue, it will be closed now.
