### ISSUE TITLE
Default List

### ISSUE THREAD

**Issue by pinae** [SecUSo/privacy-friendly-todo-list#30]
It would make sense to add a "unsorted" todo-list by default. You could add a button for creating todos to the welcome activity. The unsorted list would contain those todos.

The welcome activity should use another layout for this: First it should list the tasks from the unsorted list. After that it should use the names of the other lists as headings and display the todos in these lists below that.
That might lead to a lot of scrolling to get to the last list. To counter that you could add the list of lists into the left menu.

**Comment by Yonjuni** [comment]
Closed #30
