### ISSUE TITLE
Allow to move To-Do tasks between To-Do lists

### ISSUE THREAD

**Issue by tomikmar** [SecUSo/privacy-friendly-todo-list#35]
Allow to move To-Do tasks between To-Do lists. Now you have to remove a task and recreate it in other list.

**Comment by 0xC0FFEEC0DE** [comment]
At least in version 2.4.2 this is possible:

1. create several lists
2. create a task and select a list for it
3. long-click the task and click "edit task"
4. select a different list for the task
