### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by wonea** [SecUSo/privacy-friendly-todo-list#36]
I often use this app late at night, and would much appreciate a dark theme.

**Comment by Yonjuni** [comment]
Since the Todo-list belongs to the group of [Privacy Friendly Apps](https://secuso.org/pfa), I've opened an issue regarding your request [here](https://github.com/SecUSo/privacy-friendly-app-example/issues/9) and close this one for a better overview :-).

**Comment by wonea** [comment]
Thanks!
