### ISSUE TITLE
Setting reminder in the past should trigger it right away

### ISSUE THREAD

**Issue by licaon-kter** [SecUSo/privacy-friendly-todo-list#4]
...so this will be seen and edited to a proper future time, else that reminder would never trigger.

**Comment by 0xC0FFEEC0DE** [comment]
Hello @licaon-kter , in similar situations (illegal input) a pop-up message gets shown. I did the same here: "The reminder time cannot be in the past.". It directly tells whats wrong an is consistent with other error handling.
