### ISSUE TITLE
Everything disappeared after update from F-droid

### ISSUE THREAD

**Issue by kinclma1** [SecUSo/privacy-friendly-todo-list#42]
I don't know, whether this is only an F-droid issue, but all my lists disappeared after upgrade from 1.0.1 to 2.0

**Comment by kinclma1** [comment]
OK, it seems, that 2.0 doesn't show any tasks, not even the ones created in it.

**Comment by paulle** [comment]
Can confirm the two issues. The same happens to me after update.

**Comment by Kamuno** [comment]
This issue should now be fixed. The data should be recovered with the new version. 

Please don't delete the app data or reinstall the app because the data of version 1.0.1 will be lost if you do.

**Comment by paulle** [comment]
yes, issue is fixed in v2.1. Thank you.
