### ISSUE TITLE
Deleting subtasks does not work

### ISSUE THREAD

**Issue by rhanninen** [SecUSo/privacy-friendly-todo-list#43]
When you delete a subtask, it'll disappear, but if you leave the application and come back, then the deleted subtask is there again. I have the version 2.0 downloaded from F-droid.

**Comment by HeraldOD** [comment]
This problem is still present for me in version 2.2

**Comment by Vesdii** [comment]
Still there for me too on v2.2

**Comment by dakloifarwa** [comment]
The same here too in version 2.2, installed at LineageOS 16. Any progress on this?
Thanks!
