### ISSUE TITLE
2 issues with back button 

### ISSUE THREAD

**Issue by pangoSE** [SecUSo/privacy-friendly-todo-list#44]
1) exiting the app with back button does not work as expected (hide saving state without dialogs)
2) using back button after creating new item does not work as expected (return to list saving the new item automatically without any dialogs or warnings)

**Comment by sleep-yearning** [comment]
Could you please confirm if this is still a problem @pangoSE ?
I could not find unexpected behaviour in your described scenarios.

**Comment by sleep-yearning** [comment]
Closing this issue for now, feel free to reopen if still relevant for you.
