### ISSUE TITLE
Frequently Asked Question (FAQ) Proposal 

### ISSUE THREAD

**Issue by olayhemy** [SecUSo/privacy-friendly-todo-list#51]
Hello there, I'd like to contribute to your awesome project by writing a Frequent Asked Questions for users self-service. Would love to hear from you, thanks.

**Comment by 0xC0FFEEC0DE** [comment]
Hello @olayhemy , thanks for your offer. Please could you describe your idea of the FAQ? Where should the FAQ be located? Who is supposed to use the FAQ? Thanks!

**Comment by 0xC0FFEEC0DE** [comment]
Due to missing response I will close the issue. Please re-open it when you have more details on the FAQ.
