### ISSUE TITLE
Feature Request: Einstellung bzgl. Aufgaben-Ansicht dauerhaft gespeichert

### ISSUE THREAD

**Issue by mesophoniac** [SecUSo/privacy-friendly-todo-list#54]
Einstellung (Alle Aufgaben / Ausstehende Aufgaben / Erledigte Aufgaben) ist dauerhaft gespeichert.
(Aktuell ist es so, dass nach dem Beenden der App und Starten die letzte Einstellung (z.B. Ausstehende Aufgaben) "weg" ist. Einstellung "Alle Aufgaben" ist immer beim Start aktiv)

**Comment by 0xC0FFEEC0DE** [comment]
This issue already is fixed in current release version v2.4.2.
