### ISSUE TITLE
Feature Request: erledigte Aufgaben am Seitenende (Ansicht "Alle Aufgaben") 

### ISSUE THREAD

**Issue by mesophoniac** [SecUSo/privacy-friendly-todo-list#55]
Einstellung "erledigte Aufgaben am Seitenende/Unten) bei Ansicht "Alle Aufgaben".
(über Haken/checkbox -> [x] erledigte Aufgaben am Seitenende/Unten)

**Comment by 0xC0FFEEC0DE** [comment]
Es gibt bereits den Filter auf "Ausstehende Aufgaben". Damit werden alle erledigten Aufgaben ausgeblendet. Damit wird auch erreicht, dass die erledigten Aufgaben nicht zwischen den unerledigten stehen und ggf. dort stören.
Da sich die Funktionen sehr ähneln, würde ich diesen Vorschlag ablehnen. Sollte dennoch die Notwendigkeit für eine weitere Funktion bestehen, bitte diesen Issue mit Begründung wieder öffnen.
