### ISSUE TITLE
Feature Request: Sortierung "Nach Alphabet (A bis Z)"

### ISSUE THREAD

**Issue by mesophoniac** [SecUSo/privacy-friendly-todo-list#56]
Sortierung "Nach Alphabet (A bis Z)"
(über Haken/checkbox -> [x] Nach Alphabet sortieren)

**Comment by carmarri** [comment]
It would be very nice to have alphabetical sorting.

**Comment by alittlebitofit** [comment]
I would request alphabetical sorting too.

**Comment by 0xC0FFEEC0DE** [comment]
414628c enables sorting tasks by name.
