### ISSUE TITLE
Backup

### ISSUE THREAD

**Issue by carmarri** [SecUSo/privacy-friendly-todo-list#57]
One feature I miss is export and import, since this would allow to move all the data to a new phone or tablet. If you want to keep privacy, you can let the user pick the option to encrypt the file, but would also be nice to have a standard-plain-text export, since this would allow to export data to somewhere else like a data base.
The application is excellent, congrats.

**Comment by petermayer** [comment]
#15

**Comment by petermayer** [comment]
Please refer to #15 for any updates regarding this issue.
