### ISSUE TITLE
Always "Group by priority" option

### ISSUE THREAD

**Issue by allkreep** [SecUSo/privacy-friendly-todo-list#60]
Can you please add a setting to enable "Always group by priority". This is important because it will make everything much faster. Currently, you must open the list, and then tap the 3-dot menu, and then tick "Group by priority".

Also, there is a bug. If you tick "Group by priority" and then switch to a different list, the list is NOT grouped by priority. But the option "Group by priority" in the 3-dot menu is still ticked. You must untick the option, and then tick it again.

**Comment by 0xC0FFEEC0DE** [comment]
Hello @allkreep , at least version 2.4.2 solved both:
Setting "Group by priority" gets stored, so if you activated it once it should be permanently active.
If switching between lists, the grouping by priority gets done at every list.
