### ISSUE TITLE
Edition not saved

### ISSUE THREAD

**Issue by GrimPixel** [SecUSo/privacy-friendly-todo-list#61]
My phone is Samsung Galaxy A9s, Android version 9.
The edited notes are restored after another startup.

**Comment by alittlebitofit** [comment]
The app still has this bug.
I am using version `2.3` on Samsung Galaxy Core Prime. (`Kitkat 4.4`, `API level 19`)

**Comment by sleep-yearning** [comment]
Thanks for reporting! We are aware of a bug that should be resolved with the latest accepted pull request, however that was only directed at the edition of subtasks. Are you having problems with editions other than subtasks which don't get saved?

**Comment by alittlebitofit** [comment]
I'm so sorry I forgot to mention the exact issue as I just automatically assumed the issue was related to subtasks.
And no, I installed the app a few hours ago and up until now there's no edition issue other than subtasks. Although, I feel there are "many" features missing.

**Comment by sleep-yearning** [comment]
Thanks for clarifying, I'll close this issue now since it should be fixed in the next release.

**Comment by alittlebitofit** [comment]
Would I lose the list I made though?
