### ISSUE TITLE
Gradle can't sync

### ISSUE THREAD

**Issue by in1t3r** [SecUSo/privacy-friendly-todo-list#65]
I'm not sure whether I should report that here but as being someone who wanted to try to build your app in Android studio and maybe contribute I get an error on import of a project.
Error is gradle related I see yo guys used old gradle 3.1.0
It fails to sync project with following error:

```
ERROR: Unsupported method: AndroidProject.getVariantNames().
The version of Gradle you connect to does not support that method.
To resolve the problem you can change/upgrade the target version of Gradle you connect to.
Alternatively, you can ignore this exception and read other information from the model. 
```

Is there some changes that need to be made so that app successfully build and are there some external tools that need to be used with an app t build it.

**Comment by Kamuno** [comment]
Just upgrade gradle and it should be working fine. :) There are no external tools needed to build the app. Android Studio should automatically prompt you to upgrade.
