### ISSUE TITLE
Not possible to show tasks for an arbitrary task list

### ISSUE THREAD

**Issue by valica** [SecUSo/privacy-friendly-todo-list#66]
How to reproduce the problem:
1. Create more than three task lists.
2. Create several tasks and assign them to all task lists.
3. Use the menu at the top left and you'll see onlt two lists instead of more than three previously created.
4. Try to get the tasks associated to a list other than the two presented in the menu. It's not possible.

I can contribute to the fix.
Kind regards,
Vlad

**Comment by Kamuno** [comment]
Is the issue that you can not scroll the menu? If that is the case then 6bc4d7ae6435890cd1b87f99c5aaeb58dfad9ef3 might have fixed it.

**Comment by 0xC0FFEEC0DE** [comment]
Hello @valica , with v2.4.2 I cannot reproduce the bug. So I think its solved. Please let me know if your problem still exists.
