### ISSUE TITLE
not getting reminders

### ISSUE THREAD

**Issue by Rik44444** [SecUSo/privacy-friendly-todo-list#67]
Hi,
i'm not getting reminders that are set. 
I am using Android Pie by /e/, the privacy-safe Android. http://e.foundation/

**Comment by masscream** [comment]
Any update on thisone? I have this issue too which makes this app kind of useless. However its almost rare of its kind - really simple task app with reminders. With everything else I must fill in "the tax form" to create simple task or use some non-open source app which steals my data anyway.... Thanks

**Comment by patrickschulz** [comment]
I have the same issue. The readme says that the RECEIVE_BOOT_COMPLETE permission is necessary for this to work, but how do I enable this?

**Comment by petermayer** [comment]
Hi, thanks for reporting this! We are looking into it and will post again when a fix becomes available.

**Comment by plonibarploni** [comment]
I am also experiencing this issue. I'm running LineageOS 18.1, and I have checked all notification settings and permissions and all seems in order.

**Comment by Akalanka1337** [comment]
I have the same issue, I didn't get a reminder.

**Comment by 0xC0FFEEC0DE** [comment]
Because there are no details about this issue its hard to say what's the cause. But #115 solved an issue where the reminder service did not start. The reminder service was responsible to show the reminders. So hopefully #115 is also the fix for this issue.
