### ISSUE TITLE
Auto focus text input when adding list/task/sub-task

### ISSUE THREAD

**Issue by rnons** [SecUSo/privacy-friendly-todo-list#69]
Hi, I found this app today and really like the simplicity and privacy friendliness. Thanks for your great work.

However, I found that every time I create a new list/task/sub-task, I need to first click the + button, then click the text input to start typing. It would be nice if the text input can be auto-focused after clicking the + button.

**Comment by Kamuno** [comment]
Great suggestion, thank you.

**Comment by 0xC0FFEEC0DE** [comment]
[3c8cfa9](https://github.com/SecUSo/privacy-friendly-todo-list/commit/3c8cfa991bac45f376245da9bf16c02d10765f10) does implement that.
