### ISSUE TITLE
font skewed in vertical view

### ISSUE THREAD

**Issue by paulle** [SecUSo/privacy-friendly-todo-list#7]
Font is skewed in vertical view.
5.2 display, 1080 x 1920 pixels, font size big.
![screenshot_20161123-075146](https://cloud.githubusercontent.com/assets/4852079/20554481/913ea864-b15c-11e6-839a-ff0e126c5e96.png)
![screenshot_20161123-074939](https://cloud.githubusercontent.com/assets/4852079/20554480/913e4b62-b15c-11e6-8273-f767ae0292c1.png)

**Comment by 0xC0FFEEC0DE** [comment]
This bug seems to occur on ´layout/todo_list_entry.xml´. But I would say, this layout is not used at all in the current version of the app. If that is true, I would delete the layout and close this issue. @udenr , what do you think?

**Comment by paulle** [comment]
Yes I believe you can delete this, I reported this here in 2016 or 2017.
Thank you

Gesendet von Proton Mail für Mobilgeräte

-------- Original-Nachricht --------
Am 17. Apr. 2024, 20:41, schrieb Christian Adams :

**Comment by 0xC0FFEEC0DE** [comment]
Hello @paulle , thanks for the reply. I'm sure the shown GUI element is no longer in use. I will delete it from the repository and close this issue.
