### ISSUE TITLE
Support renaming a task list

### ISSUE THREAD

**Issue by rnons** [SecUSo/privacy-friendly-todo-list#70]
Hi, I just started playing with this app, created a list with a random name, then added some tasks. I like this app and decide to use it seriously, but can't find how to rename a list.

**Comment by adam-poteralowicz** [comment]
I've began doing that, but then I realized it's fairly easy to achieve without a single line of code. Just long-click the list and choose the "Edit" option... Do you want to have this coded anyway?

**Comment by rnons** [comment]
I just tried, long-click a list name in the sidebar or title bar doesn't seem to do anything. There is an "Edit" option when long-clicking a task, but that's a different thing.

**Comment by adam-poteralowicz** [comment]
Okay, now I can see what you're talking about. I'll handle it.

**Comment by 0xC0FFEEC0DE** [comment]
Hello @rnons , Hello @adam-poteralowicz , commit 83d41cb solves this issue.
