### ISSUE TITLE
Settings Invisible

### ISSUE THREAD

**Issue by alittlebitofit** [SecUSo/privacy-friendly-todo-list#72]
There's no `Settings` option on the sidebar.
App version: `2.3`
Phone: Samsung Galaxy Core Prime (`Kitkat 4.4`, `API 19`)

![Screenshot_2020-05-24-09-29-42](https://user-images.githubusercontent.com/42311431/82745392-49b33c00-9da1-11ea-84eb-14dfe4fd9a25.png)

**Comment by sleep-yearning** [comment]
Just leaving a note that it's probably related to Screen size (480x800px here).

**Comment by sleep-yearning** [comment]
I couldn't reproduce the issue in an emulator, however there was a (possibly related) faulty reference in the Navigation Drawer format file, which got adressed in 0e3fcc35. 

Do you have means of compiling and testing on your phone @alittlebitofit ?
This would however mean to lose your current todo-lists, as you don't have the compilation keys.

**Comment by alittlebitofit** [comment]
Ah no! I can't lose my precious todo-lists :P
I spent over an hour making them.
Is there another way?
I wish I could backup. On a side note, is backup feature going to be implemented?

**Comment by sleep-yearning** [comment]
Well if you installed it from the PlayStore I _could_ sent you a signed apk, if you installed it from F-Droid I can't. Can't comment on the backup feature, it's not yet decided when we would want to work on that.

**Comment by alittlebitofit** [comment]
I installed it from F-droid website though.

Also, is it possible if I change the package name and then install it? That way it would be installed as a separate app, right?

**Comment by sleep-yearning** [comment]
Yes, that's a good idea and should work.

**Comment by alittlebitofit** [comment]
So, after upgrading the plugin and gradle, I migrated the project to andoirdx.
Then I refactored the package name from `org.secuso.privacyfriendlytodolist` to `org.secuso.pftodolist` inside `AndroidManifest.xml` which changed everywhere.

Compilation succeeded but couldn't install.

![Screenshot at 2020-05-27 08-19-07](https://user-images.githubusercontent.com/42311431/82972497-d0ab2300-9ff2-11ea-8262-70c5d4c9bddf.png)

I don't understand key-signatures. So, I built an apk and manually tried installing it.

![Screenshot_2020-05-27-08-15-11](https://user-images.githubusercontent.com/42311431/82972560-fb957700-9ff2-11ea-8e7e-da22ec1e5043.png)

I don't know what to do from here.

**Comment by Kamuno** [comment]
The applicationId needs to be changed in the build.gradle file that is located within the app folder. Alternatively you can also just add a debug configuration that alters the applicationId. This way you will not even have to change the application id at all.

Apart from that... the error is in the activity_main.xml file.
Thanks for reporting the issue.

**Comment by alittlebitofit** [comment]
Ah! Thank you!
I can see the settings now.
NavigationView looks weird but its there!

**Comment by Kamuno** [comment]
What exactly looks weird? 🤔

**Comment by alittlebitofit** [comment]
Settings, Help and About options stay fixated on a NavigationView, while All Tasks, Calendar, etc. have a scrolling view, so I need to scroll to view even the first list.

Also, there's extra space above "To-Do" and a weird white bar on top.

![Screenshot_2020-05-29-07-31-34](https://user-images.githubusercontent.com/42311431/83212993-9a9aaa00-a17e-11ea-8527-40320285c550.png)
