### ISSUE TITLE
'isunlock' may always be false when 'onSaveInstanceState' in 'MainActivity'

### ISSUE THREAD

**Issue by AICT20** [SecUSo/privacy-friendly-todo-list#74]
I notice that in 'MainActivity', both 'onStop' and 'onSaveInstanceState' use the field 'isunlock'. However, accoding to the Android official documents, the execution order of these two lifecycle callbacks may reverse after Android API 28. 
In this case, if users use devices at or over  API 28, 'isunlock' is always set to false in 'onStop' and afterwards saved into the bundle in 'onSaveInstanceState'.

**Comment by 0xC0FFEEC0DE** [comment]
Hello @AICT20 , thanks for the hint! I read the documentation [Fragment and View CREATED](https://developer.android.com/guide/fragments/lifecycle#fragment_and_view_created_2). I think the solution is to do `isUnlocked = false` at the end of `onSaveInstanceState()`. I don't know if this is necessary but I still do that at `onStop()` if API Level < 28.
