### ISSUE TITLE
Subtasks remain unchecked when relaunching the app

### ISSUE THREAD

**Issue by Tricker-z** [SecUSo/privacy-friendly-todo-list#77]
## Description
The finished subtasks are not checked in "Complete Tasks" when the app is reopened.]

## Device Info
- Device: Pixel 2 API 27
- App version: Android 8.1.0

## Steps to Reproduce
1. download and launch To-Do List
2. add subtasks to one open task
3. check all subtasks, and the task is moved to "Complete Tasks"
4. reopen the app, the subtasks are unchecked. And if clicking the button, the task is moved to "Open Tasks"

## Actual behavior
The completed subtasks are unchecked when the app is reopened.

## Expected behavior
These subtasks remain checked in "Complete Tasks"

## Demo

<img src="https://user-images.githubusercontent.com/51984425/103122749-8f7c0e00-46bc-11eb-93b6-81ac1424dc3d.gif" width="30%"/>

**Comment by Kamuno** [comment]
should be fixed with v2.4.0
