### ISSUE TITLE
Widgets stop working after some time

### ISSUE THREAD

**Issue by Kamuno** [SecUSo/privacy-friendly-todo-list#78]
- Needs investigation
- Reported by email

**Comment by 0xC0FFEEC0DE** [comment]
Hello @Kamuno, is there more information about the issue? You mentioned an e-mail?

**Comment by 0xC0FFEEC0DE** [comment]
Hello @Kamuno , PR #122 brought many changes at the widget. They hopefully fixed the problem, so I will close this issue. Please re-open the issue if you have further information about the problem.
