### ISSUE TITLE
[Feature request] Backup/Restore function

### ISSUE THREAD

**Issue by NinjaGobbler** [SecUSo/privacy-friendly-todo-list#87]
If there is a way to include backup & restore feature on this app it will be very helpful. In scenarios where if I lose the app or my phone, I will end up losing all my to-do data which is crucial for my progress. Backup & restore from the local storage is also sufficient for a great starting point and in future some cloud storage can be considered optionally if required. Please consider.

**Comment by 0xC0FFEEC0DE** [comment]
Thanks @CrateDepth, I think this solves the issue.
