### ISSUE TITLE
Add a clear all (unmark done) option

### ISSUE THREAD

**Issue by spiliot** [SecUSo/privacy-friendly-todo-list#9]
In some use cases lists of tasks are repetitive. Manually unmarking all tasks to start over might be time consuming.

**Comment by spiliot** [comment]
Yes, exactly that. Sorry if I wasn't clear enough.

**Comment by Yonjuni** [comment]
Realized with commit 497005eb44473df65843af08029808bf034eb419
The dialog where lists can be managed now has a new item "Reset all tasks".
