### ISSUE TITLE
Delete completed tasks

### ISSUE THREAD

**Issue by udenr** [SecUSo/privacy-friendly-todo-list#92]
Add an option to delete all completed tasks

**Comment by udenr** [comment]
I think both options are fine but as a first step I would prefer a button as it might be confusing for some users if their tasks disappear automatically when they mark them as done. But having this option might also be interesting for some users.

**Comment by 0xC0FFEEC0DE** [comment]
Implemented by Commit 5121916dbbb8585421c02db0b354da0fbde32258.
