### ISSUE TITLE
Reduce friction of adding a new note.

### ISSUE THREAD

**Issue by dotancohen** [SecUSo/privacy-friendly-todo-list#94]
A few changes would greatly reduce the friction of adding a new note:

1. Instead of a single "+" button that then pops up a selection of new note types, have four separate buttons - one for each note type.
2. In the Checklist and Text note types, have the text field already focused. This will allow the user to start typing automatically.
3. In the Audio note type, start the recording immediately instead of waiting for the user to press the record button.

**Comment by 0xC0FFEEC0DE** [comment]
Hello @dotancohen, for me it seems that your issue doesn't belong to the PFA Todo List App? Am I right?

**Comment by dotancohen** [comment]
I must have been mistaken, I apologize.

**Comment by 0xC0FFEEC0DE** [comment]
No problem. I will close this, #95 and #96.
