### ISSUE TITLE
Audio note: Save button does not save

### ISSUE THREAD

**Issue by dotancohen** [SecUSo/privacy-friendly-todo-list#95]
When recording an Audio note, pressing the Save button does not actually save the note and return to the list screen. Rather, it discards the note and returns to the list screen, same as the Back arrow button.

Pressing the Save button should save the note and return to the list screen, even if it is in the middle of recording.

**Comment by 0xC0FFEEC0DE** [comment]
Hello @dotancohen, for me it seems that your issue doesn't belong to the PFA Todo List App? Am I right?
At least I don't know how saving of audio notes would belong to this app.

**Comment by 0xC0FFEEC0DE** [comment]
Closing this issue. It was a mistake like #94.
