### ISSUE TITLE
Show note creation date.

### ISSUE THREAD

**Issue by dotancohen** [SecUSo/privacy-friendly-todo-list#96]
There is currently no way to see the date and time that a note had been created. This information should be shown in the note, and possibly an option to show it on the list screen as well.

**Comment by 0xC0FFEEC0DE** [comment]
Hello @dotancohen, for me it seems that your issue doesn't belong to the PFA Todo List App? Am I right?

**Comment by 0xC0FFEEC0DE** [comment]
Closing this issue. It was a mistake like #94.
