### ISSUE TITLE
Missing info about how-to back up this app's data

### ISSUE THREAD

**Issue by jahway603** [SecUSo/privacy-friendly-todo-list#98]
Missing info about how-to back up this app's data to make it clear to users how they can do this. This is very necessary when a user is switching physical phones.

**Comment by jahway603** [comment]
PR https://github.com/SecUSo/privacy-friendly-todo-list/pull/99 resolves this issue.

**Comment by 0xC0FFEEC0DE** [comment]
As far as I can see #99 did add a note to README.md only. I think it would make sense to add such a note to the help screen of the app too.

**Comment by jahway603** [comment]
@0xC0FFEEC0DE I completely agree that it would make sense to add such a note to the help screen of the app and PR https://github.com/SecUSo/privacy-friendly-todo-list/pull/110 implements that change.

**Comment by 0xC0FFEEC0DE** [comment]
Thanks @jahway603
